experiment_name: triage_v_gate_example
seed: 42
triage_labels:
  urgent:
  - melanoma
  - melanoma_in_situ
  - bcc
  - basal cell carcinoma
  - scc
  - squamous cell carcinoma
  - atypical_nevus
  routine:
  - benign_keratosis
  - bkl
  - dermatofibroma
  - df
  - nevus
  - nv
  - vascular_lesion
  - vasc
  - akiec
  reassurance:
  - lentigo
  - lnt
  - vascular
  - normal_skin
  - normal skin
input_manifests:
  baseline: data/quality/test_manifest.csv
quality_model:
  checkpoint: models/snapcheck_quality.pt
  threshold_strategy: per_label
  thresholds:
    blur: 0.259
    motion_blur: 0.288
    low_brightness: 0.098
    high_brightness: 0.067
    low_contrast: 0.027
    high_contrast: 0.034
    noise: 0.043
    shadow: 0.168
    obstruction: 0.772
    framing: 0.049
    low_resolution: 0.054
    overall_fail: 0.5
vlm_backends:
- name: example_backend
  type: openai
  # Replace with your actual OpenAI API key
  api_key_env: OPENAI_API_KEY
  model: gpt-5-nano
  temperature: 0.0
  max_tokens: 2000
  supports_temperature: false
  retries: 6
  retry_delay: 45.0
  request_timeout: 180.0
  prompt_template: configs/prompts/diagnosis_singleline.txt
simulation:
  cache_responses: true
  cache_dir: reports/triage/cache_example
  random_subset: false
  store_reasoning_traces: true
  trace_dir: reports/triage/traces_example
metrics:
- name: triage_accuracy
- name: urgent_recall
- name: urgency_miss_rate
- name: safe_reassurance_rate
- name: token_usage
- name: latency
outputs:
  summary_csv: reports/triage/triage_detail_example.csv
  summary_backend_csv: reports/triage/triage_summary_example.csv
  partial_detail_csv: reports/triage/triage_detail_example.partial.csv
  partial_summary_csv: reports/triage/triage_summary_example.partial.csv
  confusion_matrices_dir: reports/triage/confusion_example
